; This setting makes sure that Lingotion Thespeon does not use more resources on PC than necessary.
; 0 means unconstrained use of spawned threads, which will lead to FPS drops in Unreal Engine due to resource contention.
; Anything higher than 0 sets an actual number of threads. 
; If the number is too low, some users will experience choppy audio due to generation not being fast enough.
; If the number is too high, the ONNX Runtime will compete too much with Unreal Engine, leading to frame drops.

; NOTE! It is recommended to restart the Unreal Editor after changing these settings, otherwise they might not apply correctly.
[/Script/NNERuntimeORT.NNERuntimeORTSettings]
EditorThreadingOptions=(bUseGlobalThreadPool=False,IntraOpNumThreads=8,InterOpNumThreads=8,ExecutionMode=SEQUENTIAL)